complete -c agent-observer -f -a "watch" -d "Start the live dashboard in watch mode"
complete -c agent-observer -f -a "doctor" -d "Validate configuration and print a support report"
complete -c agent-observer -l tasks-dir -r -d "Claude tasks directory"
complete -c agent-observer -l teams-dir -r -d "Claude teams directory"
complete -c agent-observer -l max-file-size -r -d "Maximum bytes to read per file"
complete -c agent-observer -l refresh-interval -r -d "TUI refresh interval"
complete -c agent-observer -l debug -d "Show debug UI"
complete -c agent-observer -l dump-json -d "Dump snapshot JSON and exit"
complete -c agent-observer -l dump-text -d "Dump snapshot text and exit"
complete -c agent-observer -l diagnostics -d "Dump diagnostics JSON and exit"
complete -c agent-observer -l version -d "Print version and exit"
complete -c agent-observer -l shell -d "Enable the local shell pane"
complete -c agent-observer -l no-shell -d "Disable the local shell pane"
complete -c agent-observer -l redact -d "Redact local paths in support output"
complete -c agent-observer -l log-file -r -d "Append structured logs to this file"
complete -c agent-observer -l log-level -r -a "debug info warn error" -d "Log level"
complete -c agent-observer -l telemetry -r -a "off on" -d "Telemetry mode"
complete -c agent-observer -l telemetry-endpoint -r -d "Telemetry endpoint URL"
complete -c agent-observer -l focus -r -a "all active blocked warnings" -d "Dump text focus"
